/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserPages;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import movieday.AdminMoviesScreen;
import movieday.Function;

/**
 *
 * @author Nino
 */
public class Screen3Login extends javax.swing.JFrame {

    String username = "";
    String password = "";

    //Databases Variables
    String jdbcDriver = "com.mysql.jdbc.Driver";
    String dbUrl = "jdbc:mysql://localhost:8889/MovieDay";
    String dbUserID = "root";
    String dbPassword = "root";

    ResultSet res;
    Connection c;

    public Screen3Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnClear.setBackground(Color.blue);
        btnLogin.setBackground(Color.blue);
        btnExit.setBackground(Color.blue);
        btnHome.setBackground(Color.blue);
        btnCreateAcc.setBackground(Color.blue);

        btnClear.setForeground(Color.white);
        btnLogin.setForeground(Color.white);
        btnExit.setForeground(Color.white);
        btnHome.setForeground(Color.white);
        btnCreateAcc.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCreateAcc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwfPassword = new javax.swing.JPasswordField();
        cbxLogInAdmin = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCreateAccount = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 580, 430));
        setMinimumSize(new java.awt.Dimension(580, 430));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(580, 430));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(570, 340));
        jPanel2.setMinimumSize(new java.awt.Dimension(570, 340));
        jPanel2.setPreferredSize(new java.awt.Dimension(570, 230));
        jPanel2.setLayout(null);

        btnLogin.setBackground(new java.awt.Color(51, 102, 255));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(90, 180, 100, 40);

        jLabel5.setBackground(new java.awt.Color(0, 51, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Forgot password?");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(260, 110, 120, 20);

        btnCreateAcc.setBackground(new java.awt.Color(51, 102, 255));
        btnCreateAcc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAcc.setText("Dont have an account?");
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateAcc);
        btnCreateAcc.setBounds(210, 180, 152, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 20, 90, 30);

        txfUsername.setBackground(new java.awt.Color(0, 0, 0));
        txfUsername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txfUsername);
        txfUsername.setBounds(200, 19, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 77, 90, 20);

        pwfPassword.setBackground(new java.awt.Color(0, 0, 0));
        pwfPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pwfPassword);
        pwfPassword.setBounds(200, 70, 180, 40);

        cbxLogInAdmin.setForeground(new java.awt.Color(255, 255, 255));
        cbxLogInAdmin.setLabel("Log in as an Admin");
        jPanel2.add(cbxLogInAdmin);
        cbxLogInAdmin.setBounds(200, 140, 160, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(12, 20, 560, 230);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(580, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 410));
        jPanel1.setLayout(null);

        btnExit.setBackground(new java.awt.Color(51, 102, 255));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(420, 270, 55, 40);

        btnHome.setBackground(new java.awt.Color(51, 102, 255));
        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(340, 270, 73, 40);

        btnClear.setBackground(new java.awt.Color(51, 102, 255));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(10, 270, 80, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 410);

        jMenu1.setText("Menu");

        mnuCreateAccount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuCreateAccount.setText("Create a new account");
        mnuCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateAccountActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCreateAccount);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);
        jMenu1.add(jSeparator3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help & About");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("FAQ");
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        char[] pass = null;
        password = "";
        try {
            pass = null;
            username = "";
            pass = pwfPassword.getPassword();
            for (int i = 0; i < pass.length; i++) {
                password += pass[i];
            }

            username = txfUsername.getText();

            if ((!(username.equals("")) || !(password.equals(""))) && cbxLogInAdmin.getState()==false) {

                Class.forName(jdbcDriver);
                c = new Function().getConnection();

                String query = "SELECT * FROM `User` WHERE Email = \""
                        + username
                        + "\" AND Password = \""
                        + password
                        + "\"\n";
                PreparedStatement preparedStmt = c.prepareStatement(query);
                ResultSet rs = preparedStmt.executeQuery(query);
                // iterate through the java resultset
                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(rootPane, "Incorrect Email and Password Combination!");
                    c.close();
                } else {
                    new Screen4_MovieReservations(rs.getInt("UserID")).setVisible(true);
                    this.setVisible(false);
                }
            }
            else if((!(username.equals("")) || !(password.equals(""))) && cbxLogInAdmin.getState()==true){
                
                Class.forName(jdbcDriver);
                c = new Function().getConnection();

                String query = "SELECT * FROM `Admin` WHERE Email = \""
                        + username
                        + "\" AND Password = \""
                        + password
                        + "\"\n";
                PreparedStatement preparedStmt = c.prepareStatement(query);
                ResultSet rs = preparedStmt.executeQuery(query);
                // iterate through the java resultset
                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(rootPane, "Incorrect Email and Password Combination!");
                    c.close();
                } else {
                    //System.out.println("Admin ID"+rs.getInt("UserID"));
                    Function.goToAdminHome(rs.getInt("UserID"));
                    this.setVisible(false);
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Please enter username and password!");
            }
        } catch (StringIndexOutOfBoundsException string) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in all the fields correctly", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Please provide data of correct data type in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Screen3Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new Screen3_1ForgotPassword().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txfUsername.setText("");
        pwfPassword.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new Screen1Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        // TODO add your handling code here:
        new Screen2Register().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void mnuCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateAccountActionPerformed
        new Screen2Register().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuCreateAccountActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen3Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen3Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen3Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen3Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen3Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogin;
    private java.awt.Checkbox cbxLogInAdmin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem mnuCreateAccount;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
