package UserPages;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import movieday.AdminMoviesScreen;
import movieday.Function;

public class Screen2Register extends javax.swing.JFrame {

    String name = "", surname = "", username = "",
            email = "", DOB = "", password = "", secQuestion = "";

    Function funct = new Function();

    //Databases Variables
    String jdbcDriver = "com.mysql.jdbc.Driver";
    String dbUrl = "jdbc:mysql://localhost:8889/MovieDay";
    String dbUserID = "root";
    String dbPassword = "root";

    int AdminID = 1;

    ResultSet res;
    Connection c;
    ResultSetMetaData meta;
    DefaultTableModel model;

    public Screen2Register() {
        initComponents();
        this.setLocationRelativeTo(null);

        btnNewPass.setEnabled(true);
        btnClear.setEnabled(true);

        btnSubmit.setEnabled(false);
        btnLogin.setEnabled(false);

        btnSubmit.setForeground(Color.GRAY);
        btnLogin.setForeground(Color.GRAY);

        btnNewPass.setBackground(Color.BLUE);
        btnClear.setBackground(Color.BLUE);
        btnBack.setBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txfSecurityQuestion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfSurname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txfDOB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnNewPass = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSignIn = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
<<<<<<< HEAD
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
=======
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        jSeparator2 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
<<<<<<< HEAD
        setMinimumSize(new java.awt.Dimension(823, 431));
        setName("Registration"); // NOI18N
=======
        setMaximumSize(new java.awt.Dimension(823, 431));
        setMinimumSize(new java.awt.Dimension(823, 431));
        setName("Registration"); // NOI18N
        setPreferredSize(new java.awt.Dimension(823, 431));
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
<<<<<<< HEAD
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
=======
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnSubmit.setBackground(new java.awt.Color(51, 102, 255));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
<<<<<<< HEAD
        btnSubmit.setToolTipText("Click to submit");
=======
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(474, 110, 120, 40);

        btnBack.setBackground(new java.awt.Color(51, 102, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
<<<<<<< HEAD
        btnBack.setToolTipText("Go to previous screen");
=======
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
<<<<<<< HEAD
        btnBack.setBounds(600, 110, 60, 40);
=======
        btnBack.setBounds(600, 110, 75, 40);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09

        btnClear.setBackground(new java.awt.Color(51, 102, 255));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
<<<<<<< HEAD
        btnClear.setToolTipText("Go to the next screen");
=======
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
<<<<<<< HEAD
        btnClear.setBounds(670, 110, 64, 40);
=======
        btnClear.setBounds(670, 110, 75, 40);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09

        txfSecurityQuestion.setBackground(new java.awt.Color(0, 0, 0));
        txfSecurityQuestion.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txfSecurityQuestion.setForeground(java.awt.Color.white);
<<<<<<< HEAD
        txfSecurityQuestion.setToolTipText("A security question in case you forget your password");
=======
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        txfSecurityQuestion.setMaximumSize(new java.awt.Dimension(4, 19));
        txfSecurityQuestion.setMinimumSize(new java.awt.Dimension(4, 19));
        txfSecurityQuestion.setPreferredSize(new java.awt.Dimension(4, 19));
        txfSecurityQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfSecurityQuestionMouseClicked(evt);
            }
        });
        txfSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSecurityQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(txfSecurityQuestion);
        txfSecurityQuestion.setBounds(474, 64, 270, 24);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("What is your mothers maden name?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 43, 250, 21);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Security Question:");
        jPanel1.add(jLabel15);
<<<<<<< HEAD
        jLabel15.setBounds(480, 20, 147, 17);
=======
        jLabel15.setBounds(480, 20, 129, 17);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3);
<<<<<<< HEAD
        jLabel3.setBounds(40, 40, 50, 17);

        txfName.setBackground(new java.awt.Color(0, 0, 0));
        txfName.setForeground(new java.awt.Color(255, 255, 255));
        txfName.setToolTipText("Enter your name");
=======
        jLabel3.setBounds(40, 40, 45, 17);

        txfName.setBackground(new java.awt.Color(0, 0, 0));
        txfName.setForeground(new java.awt.Color(255, 255, 255));
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        txfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNameActionPerformed(evt);
            }
        });
        jPanel1.add(txfName);
        txfName.setBounds(150, 30, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Surname:");
        jPanel1.add(jLabel6);
<<<<<<< HEAD
        jLabel6.setBounds(40, 80, 76, 17);

        txfSurname.setBackground(new java.awt.Color(0, 0, 0));
        txfSurname.setForeground(java.awt.Color.white);
        txfSurname.setToolTipText("Enter your surname");
=======
        jLabel6.setBounds(40, 80, 67, 17);

        txfSurname.setBackground(new java.awt.Color(0, 0, 0));
        txfSurname.setForeground(java.awt.Color.white);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        jPanel1.add(txfSurname);
        txfSurname.setBounds(150, 70, 170, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 160, 90, 17);

        txfEmail.setBackground(new java.awt.Color(0, 0, 0));
        txfEmail.setForeground(java.awt.Color.white);
<<<<<<< HEAD
        txfEmail.setToolTipText("Your email address(e.g mbizasive@gmail.com)");
=======
        txfEmail.setToolTipText("");
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        txfEmail.setMaximumSize(new java.awt.Dimension(4, 19));
        jPanel1.add(txfEmail);
        txfEmail.setBounds(150, 150, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date of Birth:");
        jPanel1.add(jLabel11);
<<<<<<< HEAD
        jLabel11.setBounds(40, 120, 105, 17);
=======
        jLabel11.setBounds(40, 120, 95, 17);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09

        txfDOB.setBackground(new java.awt.Color(0, 0, 0));
        txfDOB.setForeground(java.awt.Color.white);
        txfDOB.setText("YYYY-MM-DD");
<<<<<<< HEAD
        txfDOB.setToolTipText("Date of birth(e.g 1999-10-03)");
=======
        txfDOB.setToolTipText("");
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        txfDOB.setMaximumSize(new java.awt.Dimension(4, 19));
        jPanel1.add(txfDOB);
        txfDOB.setBounds(150, 110, 170, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Password:");
<<<<<<< HEAD
        jLabel14.setToolTipText("Your password");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 200, 84, 17);

        lblPassword.setText("<Password>");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(150, 200, 126, 15);
=======
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 200, 72, 17);

        lblPassword.setText("<Password>");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(150, 200, 126, 16);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09

        btnNewPass.setBackground(new java.awt.Color(51, 102, 255));
        btnNewPass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNewPass.setForeground(new java.awt.Color(255, 255, 255));
        btnNewPass.setText("Generate new password");
<<<<<<< HEAD
        btnNewPass.setToolTipText("Click to generate a password");
=======
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        btnNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewPass);
<<<<<<< HEAD
        btnNewPass.setBounds(40, 230, 157, 40);
=======
        btnNewPass.setBounds(40, 230, 167, 40);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 12, 820, 280);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        btnLogin.setBackground(new java.awt.Color(51, 102, 255));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
<<<<<<< HEAD
        btnLogin.setToolTipText("Log in to your account");
=======
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(620, 300, 120, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 820, 410);

        jMenu1.setText("Menu");

        mnuSignIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSignIn.setText("Sign In");
        mnuSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSignInActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSignIn);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);
        jMenu1.add(jSeparator3);

        jMenuBar1.add(jMenu1);

<<<<<<< HEAD
        jMenu2.setText("Help");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem5.setText("Help");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
=======
        jMenu2.setText("Help & About");

>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
<<<<<<< HEAD
=======

        jMenuItem5.setText("FAQ");
        jMenu2.add(jMenuItem5);
>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
        jMenu2.add(jSeparator2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNameActionPerformed

    private void btnNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPassActionPerformed
        try {
            name = (txfName.getText().trim().toLowerCase()).trim();
            surname = (txfSurname.getText().toLowerCase()).trim();
            username = (name.substring(0, 3) + surname.substring(0, 3) + Math.round(Math.random() * 899 + 100)).trim();

            password = "" + name.charAt(0) + surname.charAt(0) + Math.round(Math.random() * 89999999 + 1000000);
            lblPassword.setText(password.trim());
            btnSubmit.setEnabled(true);
            btnSubmit.setBackground(Color.BLUE);
            btnSubmit.setForeground(Color.white);
        } catch (StringIndexOutOfBoundsException string) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in all the fields correctly", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewPassActionPerformed

    private void txfSecurityQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfSecurityQuestionMouseClicked
        // TODO add your handling code here:
        txfSecurityQuestion.setText("");
    }//GEN-LAST:event_txfSecurityQuestionMouseClicked

    private void txfSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSecurityQuestionActionPerformed

    }//GEN-LAST:event_txfSecurityQuestionActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            name = txfName.getText().trim().toLowerCase();
            surname = txfSurname.getText().trim().toLowerCase();
            username = name.substring(0, 3) + surname.substring(0, 3) + Math.round(Math.random() * 899 + 100);
            secQuestion = txfSecurityQuestion.getText().trim();
            
            System.out.print(secQuestion);
            DOB = (txfDOB.getText()).trim();
            lblPassword.setText(password);
            email = txfEmail.getText();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = sdf.parse(DOB);
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());

            boolean correctEmailFormat = funct.checkEmail(email);
            //boolean correctPaswordLength = funct.checkPassword(password);

            if (!correctEmailFormat) {
                JOptionPane.showMessageDialog(rootPane, "Incorrect Email format", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (secQuestion.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Please fill in all the fields correctly", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                txfName.setEnabled(false);
                txfSurname.setEnabled(false);
                txfEmail.setEnabled(false);
                txfDOB.setEnabled(false);
                txfSecurityQuestion.setEnabled(false);

                btnClear.setEnabled(false);
                btnSubmit.setEnabled(false);

                btnLogin.setEnabled(true);
                btnNewPass.setEnabled(false);

                btnBack.setBackground(Color.BLUE);
                btnLogin.setBackground(Color.BLUE);
                btnLogin.setForeground(Color.white);

                //Database Operations
                Class.forName(jdbcDriver);
                c = new Function().getConnection();

                // the mysql insert statement
                String query = "INSERT INTO User set Name = ?, Surname = ?, DateOfBirth = ?, Email = ?, Password = ?, SecQuestionAnswer = ?";
                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = c.prepareStatement(query);

                preparedStmt.setString(1, name);
                preparedStmt.setString(2, surname);
                preparedStmt.setDate(3, sqlDate);
                preparedStmt.setString(4, email);
                preparedStmt.setString(5, password);
                preparedStmt.setString(6, secQuestion);
                // execute the preparedstatement
                preparedStmt.execute();
                
                JOptionPane.showMessageDialog(rootPane, "--------YOUR DETAILS-------- \n"
                        + "Name: \t\t" + name + "\n"
                        + "Surname: \t\t" + surname + "\n"
                        + "Email: \t" + email + "\n"
                        + "DOB: \t\t" + DOB + "\n"
                        + "Security Answer: \t" + secQuestion + "\n\n"
                        + "Username: \t\t" + username + "\n"
                        + "Password: \t\t" + password,
                        "Your details", JOptionPane.INFORMATION_MESSAGE);

                //c.close();
            }
            btnNewPass.setEnabled(false);

        } catch (StringIndexOutOfBoundsException | HeadlessException | ClassNotFoundException | SQLException | ParseException string) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in all the fields correctly", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }

        //int p = JOptionPane.showConfirmDialog(rootPane, "Are you satisfied with the data you provided?", "SUBMIT", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Screen1Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txfName.setText("");
        txfSurname.setText("");
        txfEmail.setText("");
        lblPassword.setText("<Password>");

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //JOptionPane.showMessageDialog(rootPane,"Username: " + username + "\n" + "Password: " + password, "Login details", JOptionPane.INFORMATION_MESSAGE);
        new Screen3Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void mnuSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSignInActionPerformed
        new Screen3Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuSignInActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
        new AboutScreen().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new HelpScreen().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

=======
    }//GEN-LAST:event_jMenuItem4ActionPerformed

>>>>>>> 3bc0e0938838a685967f42153c5a8d9cc784ef09
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen2Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen2Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen2Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen2Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen2Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewPass;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuSignIn;
    private javax.swing.JTextField txfDOB;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfSecurityQuestion;
    private javax.swing.JTextField txfSurname;
    // End of variables declaration//GEN-END:variables
}
