/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieday;

import javax.swing.JOptionPane;

/**
 *
 * @author johnclaude
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        viewMoviesButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewUsersButton = new javax.swing.JButton();
        viewProfileButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        adminHomeMenu = new javax.swing.JMenu();
        adminReportsMenu = new javax.swing.JMenu();
        adminMoviesMenu = new javax.swing.JMenu();
        adminUsersMenu = new javax.swing.JMenu();
        adminProfileMenu = new javax.swing.JMenu();
        adminHelpMenu = new javax.swing.JMenu();
        adminExitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        jLabel1.setText("Welcome [Admin Name]");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(800, 40, 149, 30);

        jLabel2.setText("Current Show");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 60, 120, 20);

        jLabel6.setText("Current Summary");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 450, 130, 30);

        jLabel8.setText("Seats Booked");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 490, 100, 30);

        jLabel9.setText("Seats Cancelled");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 530, 100, 30);

        jLabel7.setText("Total Sales");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 570, 100, 30);

        jButton2.setText("View Reports");
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 620, 160, 29);

        jTextField1.setText("R1080");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 570, 110, 26);

        jTextField2.setText("12");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 530, 110, 26);

        jTextField4.setText("120");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(240, 490, 110, 26);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        viewMoviesButton.setText("View Movies");
        viewMoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoviesButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewMoviesButton);
        viewMoviesButton.setBounds(100, 250, 140, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 40, 200, 200);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 40, 200, 200);

        viewUsersButton.setText("View Users");
        viewUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewUsersButton);
        viewUsersButton.setBounds(410, 250, 140, 40);

        viewProfileButton.setText("View Profile");
        viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewProfileButton);
        viewProfileButton.setBounds(710, 250, 140, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(680, 40, 200, 200);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 90, 970, 330);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 660));

        adminHomeMenu.setText("Home");
        adminHomeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminHomeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(adminHomeMenu);

        adminReportsMenu.setText("Reports");
        adminReportsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminReportsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(adminReportsMenu);

        adminMoviesMenu.setText("Movies");
        adminMoviesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMoviesMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(adminMoviesMenu);

        adminUsersMenu.setText("Users");
        adminUsersMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminUsersMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(adminUsersMenu);

        adminProfileMenu.setText("Profile");
        adminProfileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminProfileMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(adminProfileMenu);

        adminHelpMenu.setText("Help");
        adminHelpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminHelpMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(adminHelpMenu);

        adminExitMenu.setText("Exit");
        adminExitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminExitMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(adminExitMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminReportsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminReportsMenuMouseClicked
        Function.goToReportScreen();
        this.setVisible(false);
    }//GEN-LAST:event_adminReportsMenuMouseClicked

    private void adminHomeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminHomeMenuMouseClicked
       Function.goToAdminHome();
       this.setVisible(false);
    }//GEN-LAST:event_adminHomeMenuMouseClicked

    private void adminMoviesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMoviesMenuMouseClicked
       Function.goToAdminMoviesScreen();
       this.setVisible(false);
    }//GEN-LAST:event_adminMoviesMenuMouseClicked

    private void adminUsersMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUsersMenuMouseClicked
       Function.goToAdminUserScreen();
       this.setVisible(false);
    }//GEN-LAST:event_adminUsersMenuMouseClicked

    private void adminProfileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminProfileMenuMouseClicked
        Function.goToAdminUserScreen();
        this.setVisible(false);
    }//GEN-LAST:event_adminProfileMenuMouseClicked

    private void adminHelpMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminHelpMenuMouseClicked
        Function.goToAdminHelpScreen();
        this.setVisible(false);
    }//GEN-LAST:event_adminHelpMenuMouseClicked

    private void adminExitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminExitMenuMouseClicked
       int choice  = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?");
       if(choice == 0){
           System.exit(0);
       }
    }//GEN-LAST:event_adminExitMenuMouseClicked

    private void viewMoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMoviesButtonActionPerformed
       Function.goToAdminMoviesScreen();
       this.setVisible(false);
    }//GEN-LAST:event_viewMoviesButtonActionPerformed

    private void viewUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersButtonActionPerformed
      Function.goToAdminUserScreen();
      this.setVisible(false);
    }//GEN-LAST:event_viewUsersButtonActionPerformed

    private void viewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButtonActionPerformed
      Function.goToAdminUserScreen();
      this.setVisible(false);
    }//GEN-LAST:event_viewProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminExitMenu;
    private javax.swing.JMenu adminHelpMenu;
    private javax.swing.JMenu adminHomeMenu;
    private javax.swing.JMenu adminMoviesMenu;
    private javax.swing.JMenu adminProfileMenu;
    private javax.swing.JMenu adminReportsMenu;
    private javax.swing.JMenu adminUsersMenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton viewMoviesButton;
    private javax.swing.JButton viewProfileButton;
    private javax.swing.JButton viewUsersButton;
    // End of variables declaration//GEN-END:variables
}
