/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieday;

/**
 *
 * @author johnclaude
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ReportsMenu = new javax.swing.JMenu();
        MoviesMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        jLabel1.setText("Welcome [Admin Name]");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 30, 149, 16);

        jLabel2.setText("Current Show");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 60, 120, 20);

        jLabel6.setText("Current Summary");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 450, 130, 30);

        jLabel8.setText("Seats Booked");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 490, 100, 30);

        jLabel9.setText("Seats Cancelled");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 530, 100, 30);

        jLabel7.setText("Total Sales");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 570, 100, 30);

        jButton2.setText("View Reports");
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 620, 160, 29);

        jTextField1.setText("R1080");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 570, 110, 26);

        jTextField2.setText("12");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 530, 110, 26);

        jTextField4.setText("120");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(240, 490, 110, 26);

        jPanel2.setLayout(null);

        jButton1.setText("View Movies");
        jPanel2.add(jButton1);
        jButton1.setBounds(90, 250, 140, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 40, 200, 200);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(310, 40, 200, 200);

        jButton3.setText("View Users");
        jPanel2.add(jButton3);
        jButton3.setBounds(330, 250, 140, 29);

        jButton4.setText("View Profile");
        jPanel2.add(jButton4);
        jButton4.setBounds(560, 250, 140, 29);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(540, 40, 200, 200);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 90, 770, 330);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 660));

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        ReportsMenu.setText("Reports");
        ReportsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ReportsMenu);

        MoviesMenu.setText("Movies");
        jMenuBar1.add(MoviesMenu);

        jMenu2.setText("Users");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profile");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exit");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMenuMouseClicked
    }//GEN-LAST:event_ReportsMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MoviesMenu;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
