/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieday;

/**
 *
 * @author johnclaude
 */
public class AdminMoviesScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminMoviesScreen
     */
    public AdminMoviesScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ReportsMenu = new javax.swing.JMenu();
        MoviesMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 725));
        setResizable(false);
        setSize(new java.awt.Dimension(960, 725));
        getContentPane().setLayout(null);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(770, 640));

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 80, 200, 180);

        jLabel2.setText("Length");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 370, 50, 30);

        jLabel3.setText("Year");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 320, 80, 30);

        jLabel5.setText("Title");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 280, 80, 30);

        jLabel6.setText("Description");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 430, 120, 20);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(90, 280, 160, 30);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(90, 370, 160, 30);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(90, 320, 160, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(40, 470, 210, 130);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 20, 300, 620);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(40, 80, 200, 180);

        jLabel9.setText("Length");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 370, 50, 30);

        jLabel10.setText("Year");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 320, 80, 30);

        jLabel11.setText("Title");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(40, 280, 80, 30);

        jLabel12.setText("Description");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 430, 120, 20);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(90, 280, 160, 30);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(90, 370, 160, 30);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(90, 320, 160, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(40, 470, 210, 130);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(600, 20, 300, 620);

        jPanel5.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(40, 80, 200, 180);

        jLabel13.setText("Length");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(40, 370, 50, 30);

        jLabel14.setText("Year");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(40, 320, 80, 30);

        jLabel15.setText("Title");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(40, 280, 80, 30);

        jLabel16.setText("Description");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(40, 430, 120, 20);
        jPanel5.add(jTextField8);
        jTextField8.setBounds(90, 280, 160, 30);
        jPanel5.add(jTextField9);
        jTextField9.setBounds(90, 370, 160, 30);
        jPanel5.add(jTextField10);
        jTextField10.setBounds(90, 320, 160, 30);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(40, 470, 210, 130);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(300, 20, 300, 620);

        jButton2.setText("Save Changes");
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 650, 180, 40);

        jTabbedPane1.addTab("Show 1-15:00", jPanel1);

        jPanel3.setLayout(null);

        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel7.add(jLabel17);
        jLabel17.setBounds(40, 80, 200, 180);

        jLabel19.setText("Length");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(40, 370, 50, 30);

        jLabel20.setText("Year");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(40, 320, 80, 30);

        jLabel21.setText("Title");
        jPanel7.add(jLabel21);
        jLabel21.setBounds(40, 280, 80, 30);

        jLabel22.setText("Description");
        jPanel7.add(jLabel22);
        jLabel22.setBounds(40, 430, 120, 20);
        jPanel7.add(jTextField11);
        jTextField11.setBounds(90, 280, 160, 30);
        jPanel7.add(jTextField12);
        jTextField12.setBounds(90, 370, 160, 30);
        jPanel7.add(jTextField13);
        jTextField13.setBounds(90, 320, 160, 30);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jPanel7.add(jScrollPane5);
        jScrollPane5.setBounds(40, 470, 210, 130);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(10, 20, 300, 620);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel8.add(jLabel23);
        jLabel23.setBounds(40, 80, 200, 180);

        jLabel24.setText("Length");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(40, 370, 50, 30);

        jLabel25.setText("Year");
        jPanel8.add(jLabel25);
        jLabel25.setBounds(40, 320, 80, 30);

        jLabel26.setText("Title");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(40, 280, 80, 30);

        jLabel27.setText("Description");
        jPanel8.add(jLabel27);
        jLabel27.setBounds(40, 430, 120, 20);
        jPanel8.add(jTextField14);
        jTextField14.setBounds(90, 280, 160, 30);
        jPanel8.add(jTextField15);
        jTextField15.setBounds(90, 370, 160, 30);
        jPanel8.add(jTextField16);
        jTextField16.setBounds(90, 320, 160, 30);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        jPanel8.add(jScrollPane6);
        jScrollPane6.setBounds(40, 470, 210, 130);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(600, 20, 300, 620);

        jPanel9.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel9.add(jLabel28);
        jLabel28.setBounds(40, 80, 200, 180);

        jLabel29.setText("Length");
        jPanel9.add(jLabel29);
        jLabel29.setBounds(40, 370, 50, 30);

        jLabel30.setText("Year");
        jPanel9.add(jLabel30);
        jLabel30.setBounds(40, 320, 80, 30);

        jLabel31.setText("Title");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(40, 280, 80, 30);

        jLabel32.setText("Description");
        jPanel9.add(jLabel32);
        jLabel32.setBounds(40, 430, 120, 20);
        jPanel9.add(jTextField17);
        jTextField17.setBounds(90, 280, 160, 30);
        jPanel9.add(jTextField18);
        jTextField18.setBounds(90, 370, 160, 30);
        jPanel9.add(jTextField19);
        jTextField19.setBounds(90, 320, 160, 30);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane7.setViewportView(jTextArea6);

        jPanel9.add(jScrollPane7);
        jScrollPane7.setBounds(40, 470, 210, 130);

        jPanel6.add(jPanel9);
        jPanel9.setBounds(300, 20, 300, 620);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 0, 920, 650);

        jButton1.setText("Save Changes");
        jPanel3.add(jButton1);
        jButton1.setBounds(350, 650, 180, 40);

        jTabbedPane1.addTab("Show 2-17:00", jPanel3);

        jPanel10.setLayout(null);

        jPanel11.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel12.add(jLabel18);
        jLabel18.setBounds(40, 80, 200, 180);

        jLabel33.setText("Length");
        jPanel12.add(jLabel33);
        jLabel33.setBounds(40, 370, 50, 30);

        jLabel34.setText("Year");
        jPanel12.add(jLabel34);
        jLabel34.setBounds(40, 320, 80, 30);

        jLabel35.setText("Title");
        jPanel12.add(jLabel35);
        jLabel35.setBounds(40, 280, 80, 30);

        jLabel36.setText("Description");
        jPanel12.add(jLabel36);
        jLabel36.setBounds(40, 430, 120, 20);
        jPanel12.add(jTextField20);
        jTextField20.setBounds(90, 280, 160, 30);
        jPanel12.add(jTextField21);
        jTextField21.setBounds(90, 370, 160, 30);
        jPanel12.add(jTextField22);
        jTextField22.setBounds(90, 320, 160, 30);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane8.setViewportView(jTextArea7);

        jPanel12.add(jScrollPane8);
        jScrollPane8.setBounds(40, 470, 210, 130);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(10, 20, 300, 620);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(null);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel13.add(jLabel37);
        jLabel37.setBounds(40, 80, 200, 180);

        jLabel38.setText("Length");
        jPanel13.add(jLabel38);
        jLabel38.setBounds(40, 370, 50, 30);

        jLabel39.setText("Year");
        jPanel13.add(jLabel39);
        jLabel39.setBounds(40, 320, 80, 30);

        jLabel40.setText("Title");
        jPanel13.add(jLabel40);
        jLabel40.setBounds(40, 280, 80, 30);

        jLabel41.setText("Description");
        jPanel13.add(jLabel41);
        jLabel41.setBounds(40, 430, 120, 20);
        jPanel13.add(jTextField23);
        jTextField23.setBounds(90, 280, 160, 30);
        jPanel13.add(jTextField24);
        jTextField24.setBounds(90, 370, 160, 30);
        jPanel13.add(jTextField25);
        jTextField25.setBounds(90, 320, 160, 30);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane9.setViewportView(jTextArea8);

        jPanel13.add(jScrollPane9);
        jScrollPane9.setBounds(40, 470, 210, 130);

        jPanel11.add(jPanel13);
        jPanel13.setBounds(600, 20, 300, 620);

        jPanel14.setLayout(null);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieday/images/Folder.jpg"))); // NOI18N
        jPanel14.add(jLabel42);
        jLabel42.setBounds(40, 80, 200, 180);

        jLabel43.setText("Length");
        jPanel14.add(jLabel43);
        jLabel43.setBounds(40, 370, 50, 30);

        jLabel44.setText("Year");
        jPanel14.add(jLabel44);
        jLabel44.setBounds(40, 320, 80, 30);

        jLabel45.setText("Title");
        jPanel14.add(jLabel45);
        jLabel45.setBounds(40, 280, 80, 30);

        jLabel46.setText("Description");
        jPanel14.add(jLabel46);
        jLabel46.setBounds(40, 430, 120, 20);
        jPanel14.add(jTextField26);
        jTextField26.setBounds(90, 280, 160, 30);
        jPanel14.add(jTextField27);
        jTextField27.setBounds(90, 370, 160, 30);
        jPanel14.add(jTextField28);
        jTextField28.setBounds(90, 320, 160, 30);

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane10.setViewportView(jTextArea9);

        jPanel14.add(jScrollPane10);
        jScrollPane10.setBounds(40, 470, 210, 130);

        jPanel11.add(jPanel14);
        jPanel14.setBounds(300, 20, 300, 620);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(0, 0, 920, 650);

        jButton3.setText("Save Changes");
        jPanel10.add(jButton3);
        jButton3.setBounds(350, 650, 180, 40);

        jTabbedPane1.addTab("Show 3-19:00", jPanel10);

        jPanel15.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nino Jacobs", "Infinity War", "15:00", "2", "234"},
                {"Sive Mbiza", "Black Panther", "17:00", "4", "231"},
                {"Kamo Matjila", "Black Panther", "17:00", "8", "231"},
                {"John Claude", "50 Shades", "19:00", "2", "233"}
            },
            new String [] {
                "Full Name", "Movie", "Time", "Number Of Seats", "Resrvation ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jTable1);

        jPanel15.add(jScrollPane11);
        jScrollPane11.setBounds(30, 170, 640, 210);

        jLabel1.setText("Manage Reservations");
        jPanel15.add(jLabel1);
        jLabel1.setBounds(30, 60, 230, 40);

        jLabel47.setText("Search");
        jPanel15.add(jLabel47);
        jLabel47.setBounds(40, 110, 41, 30);
        jPanel15.add(jTextField1);
        jTextField1.setBounds(100, 110, 120, 40);

        jButton4.setText("Go");
        jPanel15.add(jButton4);
        jButton4.setBounds(230, 110, 90, 40);

        jButton5.setText("Delete Selected");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton5);
        jButton5.setBounds(30, 390, 150, 50);

        jTabbedPane1.addTab("Manage Reservations", jPanel15);

        jScrollPane4.setViewportView(jTabbedPane1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(0, 0, 960, 760);

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        ReportsMenu.setText("Reports");
        ReportsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ReportsMenu);

        MoviesMenu.setText("Movies");
        jMenuBar1.add(MoviesMenu);

        jMenu2.setText("Users");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profile");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exit");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMenuMouseClicked

    }//GEN-LAST:event_ReportsMenuMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMoviesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMoviesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMoviesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMoviesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMoviesScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MoviesMenu;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
